=== Beben107700/JRoborally/src/main/resources/xsd/board.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.ockerman.be/roborally"
            xmlns="http://www.ockerman.be/roborally" elementFormDefault="qualified">
            
    <xsd:element name="board" type="board"></xsd:element>
    
    <xsd:complexType name="board">
    	<xsd:sequence>
    		<xsd:element name="tiles" type="tileDescriptorPhraseType" maxOccurs="1" minOccurs="1" ></xsd:element>
    	</xsd:sequence>
    	<xsd:attribute name="sizex" type="xsd:int"></xsd:attribute>
    	<xsd:attribute name="sizey" type="xsd:int"></xsd:attribute>
    </xsd:complexType>



    <xsd:complexType name="tileBase">
    	<xsd:attribute name="orientation" type="orientationType" use="optional" default="random"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="tileDescriptorPhraseType">
    	<xsd:sequence>
    		<xsd:choice minOccurs="0" maxOccurs="unbounded" >
    			<xsd:element name="at" type="positionTilePhrase"></xsd:element>
    			<xsd:element name="range" type="areaTilePhrase"></xsd:element>
    		</xsd:choice>
    	</xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="positionTilePhrase">
        <xsd:sequence>
	        <xsd:choice minOccurs="1" maxOccurs="1" >
                <xsd:element name="belt" type="beltTile"></xsd:element>
                <xsd:element name="fastbelt" type="fastbeltTile"></xsd:element>
                <xsd:element name="hole" type="holeTile"></xsd:element>
                <xsd:element name="leftgear" type="leftgearTile"></xsd:element>
                <xsd:element name="rightgear" type="rightgearTile"></xsd:element>
                <xsd:element name="repair" type="repairTile"></xsd:element>
                <xsd:element name="double-repair" type="doubleRepairTile"></xsd:element>
            </xsd:choice>
         </xsd:sequence>
        <xsd:attribute name="x" type="xsd:int" use="required"/>
        <xsd:attribute name="y" type="xsd:int" use="required"/>
    </xsd:complexType>
    
    <xsd:complexType name="areaTilePhrase">
        <xsd:sequence>
            <xsd:choice minOccurs="1" maxOccurs="1" >
                <xsd:element name="belt" type="beltTile"></xsd:element>
                <xsd:element name="fastbelt" type="fastbeltTile"></xsd:element>
                <xsd:element name="hole" type="holeTile"></xsd:element>
                <xsd:element name="leftgear" type="leftgearTile"></xsd:element>
                <xsd:element name="rightgear" type="rightgearTile"></xsd:element>
            </xsd:choice>
         </xsd:sequence>
         <xsd:attribute name="from-x" type="xsd:int" use="required"/>
         <xsd:attribute name="from-y" type="xsd:int" use="required"/>
         <xsd:attribute name="to-x" type="xsd:int" use="required"/>
         <xsd:attribute name="to-y" type="xsd:int" use="required"/>
    </xsd:complexType>


    <xsd:complexType name="beltTile">
        <xsd:complexContent>
            <xsd:extension base="tileBase"></xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>
    
    <xsd:complexType name="fastbeltTile">
    	<xsd:complexContent>
    		<xsd:extension base="tileBase"></xsd:extension>
    	</xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="holeTile"></xsd:complexType>

    <xsd:complexType name="leftgearTile">
    </xsd:complexType>

    <xsd:complexType name="rightgearTile"></xsd:complexType>
    
    <xsd:complexType name="repairTile">
        <xsd:complexContent>
            <xsd:extension base="tileBase"></xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>
    
    <xsd:complexType name="doubleRepairTile">
        <xsd:complexContent>
            <xsd:extension base="tileBase"></xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>
    

    <xsd:simpleType name="orientationType">
    	<xsd:restriction base="xsd:string">
    		<xsd:enumeration value="left"></xsd:enumeration>
    		<xsd:enumeration value="right"></xsd:enumeration>
    		<xsd:enumeration value="up"></xsd:enumeration>
    		<xsd:enumeration value="down"></xsd:enumeration>
    		<xsd:enumeration value="random"></xsd:enumeration>
    	</xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== Beben107700/JRoborally/src/main/resources/boards/island.xml
<?xml version="1.0" encoding="UTF-8"?>
<board xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns="http://www.ockerman.be/roborally" 
       xsi:schemaLocation="http://www.ockerman.be/roborally ../xsd/board.xsd" sizex="12" sizey="12">   
  <tiles>
    <range from-x="3" from-y="3" to-x="9" to-y="3"><belt orientation="left"/></range>
    <range from-x="3" from-y="4" to-x="3" to-y="9"><belt orientation="up"/></range>
    <range from-x="4" from-y="10" to-x="9" to-y="10"><belt orientation="right"/></range>
    <range from-x="10" from-y="9" to-x="10" to-y="3"><belt orientation="down"/></range>
    
    <range from-x="5" from-y="4" to-x="8" to-y="4"><belt orientation="right"/></range>
    <range from-x="7" from-y="6" to-x="8" to-y="6"><belt orientation="right"/></range>
    
    <range from-x="5" from-y="9" to-x="8" to-y="9"><belt orientation="left"/></range>
    <range from-x="7" from-y="6" to-x="8" to-y="6"><belt orientation="left"/></range>
    
    <range from-x="9" from-y="5" to-x="9" to-y="8"><belt orientation="up"/></range>
    <range from-x="4" from-y="5" to-x="4" to-y="8"><belt orientation="down"/></range>
    
    <at x="1" y="3"><repair/></at>
    <at x="12" y="12"><repair/></at>
    <at x="7" y="7"><double-repair/></at>
    
    <at x="2" y="2"><hole/></at>
    <at x="2" y="3"><hole/></at>
    <at x="3" y="2"><hole/></at>
    
    <at x="10" y="2"><hole/></at>
    <at x="11" y="2"><hole/></at>
    <at x="11" y="3"><hole/></at>
    
    <at x="2" y="10"><hole/></at>
    <at x="2" y="11"><hole/></at>
    <at x="3" y="11"><hole/></at>
    
    <at x="11" y="11"><hole/></at>
    <at x="10" y="11"><hole/></at>
    <at x="11" y="10"><hole/></at>
    
    <at x="5" y="5"><hole/></at>
    <at x="5" y="6"><hole/></at>
    <at x="6" y="5"><hole/></at>
    
    <at x="8" y="8"><hole/></at>
    <at x="8" y="7"><hole/></at>
    <at x="7" y="8"><hole/></at>
    
    <at x="4" y="4"><leftgear/></at>
    <at x="4" y="9"><leftgear/></at>
    <at x="9" y="9"><leftgear/></at>
    <at x="9" y="4"><leftgear/></at>
    
    <at x="3" y="10"><rightgear/></at>
    <at x="10" y="10"><rightgear/></at>
  
  </tiles>
  
      <!--  //left_belt  from  3, 3 to  9, 3
			//up_belt    from  3, 4 to  3, 9
			//right_belt from  4,10 to  9,10
			//down_belt  from 10, 9 to 10, 3
			
			//right_belt from  5, 4 to  8, 4
			//right_belt from  7, 6 to  8, 6
			  
			//left_belt  from  5, 9 to  8, 9
			//left_belt  from  5, 7 to  6, 7
			
			//up_belt    from  9, 5 to  9, 8
			//down_belt  from  4, 5 to  4, 8
			    
			_repairpoint at 1,3 ; 12,12
			_repairpoint2 at 7,7
			
			//_hole at  2, 2 ;  2, 3  ;  3, 2 ; 10, 2 ; 11, 2 ; 11, 3
			//_hole at  2,10 ;  2,11  ;  3,11 ; 11,11 ; 10,11 ; 11,10
			_hole at  5, 5 ;  5, 6  ;  6, 5 ;  8, 8 ;  8, 7 ; 7 , 8
			
			//left_gear at  4, 4 ;  4, 9 ;  9, 9 ;  9, 4
			//right_gear        at  3,10 ; 10,10
			
			left_wall  at  1, 3 ;  1, 5 ;  1, 8 ;  1,10 ; 10, 6
			right_wall at  3, 7 ; 12, 3 ; 12, 5 ; 12, 8 ; 12,10
			up_wall    at  3,12 ;  5,12 ;  8,12 ; 10,12 ;  6, 3 
			down_wall  at  3, 1 ;  5, 1 ;  8, 1 ; 10, 1 ;  6,10 
			 
			left_wall from 1,1 to 1,12
			right_wall from 12,1 to 12,12
			up_wall from 1,12 to 12,12
			down_wall from 1,1 to 12,1  
			
			horizontal_laser from 1,1 to 12,1
			
		-->
  
</board>
